### ISSUE TITLE
plz watch loop on fail

### ISSUE THREAD

**Issue by tikal** [thought-machine/please#658] opened 2019-06-19 01:24 UTC
Trying out the command `plz watch //.:all` to test if can automatically have my tests running after a file change. It works fine when the tests are passing but loops infinitely when a test is broken (until it is fixed again). 
Is this behaviour here the expected one ? If yes, I'm will consider adding an option to stop on failure.

**Comment by peterebden** [comment] 2019-06-19 17:05
That isn't the expected behaviour, no - it should only trigger again on changes to files. I can't reproduce it locally though 🤔

**Comment by tikal** [comment] 2019-06-19 18:35
Can you try this use case?
```
mkdir issues-658
cd issues-658
echo 'python_binary(
    name = "a",
    main = "a.py"
)
python_test(
    name = "a_test",
    srcs = ["test_a.py"],
    deps = [":a"],
)' > BUILD
touch a.py
echo 'from a import a' > test_a.py
plz init
plz watch //.:all
```

**Comment by peterebden** [comment] 2019-06-20 11:29
That doesn't trigger a loop for me - the test fails as expected but only once.
Have to confess I'm a little mystified about what's going on here...

**Comment by tikal** [comment] 2019-06-20 14:57
It happens for me. I'll look into it.

**Comment by agenticarus** [comment] 2019-08-28 10:53
Closing for now, please reopen if behaviour reappears/continues.

**Closed by agenticarus** 2019-08-28 10:53 UTC
