### ISSUE TITLE
Please installation does not respect the env python (specifically when looking for `cffi`)

### ISSUE THREAD

**Issue by natpen** [thought-machine/please#253] opened 2017-12-06 19:39 UTC
I'm not sure how necessary that is, but I'm forced to install `python-pip` on Linux, then pip install cffi using that system pip. Everything else in please respects the path configuration in a `plzconfig`, which allows me to preface the system python places with pyenv shim places, and so get a pyenv-controlled Python installation to take care of all python things. Is it possible to get the bootstrapping to either respect the path entries in a `plzconfig`, or be configurable some other way?

**Comment by peterebden** [comment] 2017-12-07 13:45
Hmmmm must be possible :) Just to be sure I understand this correctly - is it when running the bootstrap command at compile time, or when you run plz later and it tries to load the parser - or both?

**Comment by natpen** [comment] 2017-12-07 13:59
This is happening at `plz init` time.

Less certain about compile time, but can check that out too when I have a minute :)

**Comment by peterebden** [comment] 2017-12-07 14:14
OK, thanks. I'll try to refresh my memory about how that locates it and maybe have a play with pyenv.

**Comment by peterebden** [comment] 2017-12-08 11:36
Right, so when I said "must be possible" that maybe needed more consideration...

The problem isn't the path that `python` is on, it's resolving the library via the dynamic linker. I have managed to get it to work by doing
```
env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 2.7.9
pyenv global 2.7.9
pip install cffi
LD_LIBRARY_PATH="/home/peter/git/pyenv/versions/2.7.9/lib/"
plz query print //src:please
```
That's quite the fiddle though. You'd always need the `PYTHON_CONFIGURE_OPTS` bit since we need the shared library, and I don't think it's possible to adjust `LD_LIBRARY_PATH` dynamically within an already-running program (might be wrong on that though). That's probably the ugliest bit since pyenv wouldn't switch it for you.

I'll keep thinking on it. Ideally we would have less of a dependency on system Python for this stuff but it's not easy to achieve that with cffi embedding. There is also an option to download a portable PyPy distribution to use but that only works for Linux right now.

**Comment by natpen** [comment] 2017-12-09 14:09
Eep! Okay. Thank you for the help investigating :hugs: totally understand about the challenges due to cffi embedding.

I don't think permanently modifying `LD_LIBRARY_PATH` would be a good habit to get into, so I'll fall back to the system cffi for now. I can also add some documentation about this for posterity.

**Closed** 2017-12-10 20:00 UTC
