### ISSUE TITLE
cc_test is failing

### ISSUE THREAD

**Issue by cinemast** [thought-machine/please#577] opened 2019-03-27 11:10 UTC
I get the same error as here: https://circleci.com/gh/thought-machine/please-examples/22.

```
///third_party/cc/unittest_cpp//:unittest_cpp depends on //third_party/cc:all, but the directory third_party/cc doesn't exist
    ///third_party/cc/unittest_cpp//:unittest_cpp
///third_party/cc/unittest_cpp//:unittest_cpp depends on //third_party/cc:all, but the directory third_party/cc doesn't exist
````

Does someone have an insight on that?

**Comment by peterebden** [comment] 2019-04-11 11:49
OK took a bit of investigation (sorry for the slow reply)... the issue is to do with fetching the unittest runner from a subrepo, and it trying to depend on another subrepo there.

Thinking about how we should best handle this, will see what I can come up with.

**Comment by peterebden** [comment] 2019-04-11 12:18
Okay, the above should solve I think; it will fall back to looking in the appropriate place.

**Comment by agenticarus** [comment] 2019-08-28 10:47
Marking as resolved - if this still occurs, please reopen.

**Closed by agenticarus** 2019-08-28 10:47 UTC

**Comment by cpg314** [comment] 2021-02-13 10:32
It seems like this happens (latest release):
- `please init` in a new folder.
- BUILD file with content
```
github_repo(
  name = "pleasings",
  repo = "thought-machine/pleasings",
  revision = "master",
)
cc_test(
    name="test",
    srcs=["test.cpp"],
)

```
- `test.cpp` file with only a main.
$please run :test
```
Build stopped after 60ms. 1 target failed:
    ///third_party/cc/unittest_cpp//:unittest_cpp
///third_party/cc/unittest_cpp//:unittest_cpp depends on //third_party/cc:all, but the directory third_party/cc doesn't exist: third_party/cc
```
